In [6]:
from spc_ads_pub.msg import CableLength
from geometry_msgs.msg import PoseStamped
from liegroups.numpy import SO3
import numpy as np

In [25]:
SO3.from_matrix(np.eye(3)).to_quaternion(normalized = True)

TypeError: to_quaternion() got an unexpected keyword argument 'normalized'

In [6]:
import rospy
rospy.init_node('tmp_node')

In [49]:
rospy.Time.now().to_sec()

1643293256.5689144

In [13]:
msg = CableLength()

In [16]:
msg.header.stamp.to_sec()

0.0

In [42]:
msg = PoseStamped()

In [43]:
msg.pose.position

x: 0.0
y: 0.0
z: 0.0

In [41]:
q = SO3.from_matrix(np.eye(3)).to_quaternion()
msg.pose.orientation.w = q[0]
msg.pose.orientation.x = q[1]
msg.pose.orientation.y = q[2]
msg.pose.orientation.z = q[3]

# Send a Request to Set Initial Cable Lengths

In [14]:
from scampi_ks_ros.srv import CableLenInit
import rospy

In [15]:
init_cable_lengths = rospy.ServiceProxy('/scampi_ks_ros/init_cable_lengths', CableLenInit)

In [41]:
eq_pose = PoseStamped()
eq_pose.pose.orientation.x = 0.0202
eq_pose.pose.orientation.y = 0.0631
eq_pose.pose.orientation.z = -0.0582
eq_pose.pose.orientation.w = 0.9961
eq_pose.pose.position.x = 0.0402
eq_pose.pose.position.y = -1.1387
eq_pose.pose.position.z = 3.9743

eq_len = [8.6661,    8.8732,    7.8163,    7.5852]
init_cable_lengths(eq_pose, eq_len)

result: 1

In [34]:
R = np.random.randn(3,3)
u, s, v = np.linalg.svd(R)
R

array([[-1.23169967,  0.27391196, -0.53892053],
       [-0.75227936,  0.77288847, -0.75757052],
       [ 0.54258042, -1.26354574, -0.4039983 ]])

In [29]:
np.linalg.svd(u.T@v)

(array([[-0.3008452 ,  0.95257861, -0.04567452],
        [-0.06353995,  0.02776557,  0.99759298],
        [ 0.95155391,  0.30302321,  0.05217366]]),
 array([1., 1., 1.]),
 array([[-0., -1., -0.],
        [-0., -0., -1.],
        [-1., -0., -0.]]))

In [38]:
u, s, v = np.linalg.svd(R)
u@v

array([[-0.97140489, -0.21422443, -0.10237403],
       [-0.03475349,  0.55482542, -0.83124061],
       [ 0.23487176, -0.80391333, -0.54640517]])